apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ken027/ticketing-auth-service
      context: auth-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ken027/ticketing-ticket-service
      context: ticket-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ken027/ticketing-order-service
      context: order-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ken027/ticketing-expiration-service
      context: expiration-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ken027/ticketing-payment-service
      context: payment-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
profiles:
  - name: ticketing-docker-prod
    build:
      local:
        push: false
      artifacts:
        - image: ken027/ticketing-auth-service
          context: auth-service
          docker:
            dockerfile: Dockerfile.prod
        - image: ken027/ticketing-ticket-service
          context: ticket-service
          docker:
            dockerfile: Dockerfile.prod
        - image: ken027/ticketing-order-service
          context: order-service
          docker:
            dockerfile: Dockerfile.prod
        - image: ken027/ticketing-expiration-service
          context: expiration-service
          docker:
            dockerfile: Dockerfile.prod
        - image: ken027/ticketing-payment-service
          context: payment-service
          docker:
            dockerfile: Dockerfile.prod
