FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./

RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./

RUN npm install --omit=dev

COPY --from=builder /app/build ./build

EXPOSE 5000

CMD ["npm", "start"]
