# Use a multi-stage build to keep the final image small
FROM node:22-alpine AS builder

WORKDIR /app
COPY package*.json ./

RUN npm install --omit=dev
COPY . .
RUN npm run build

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/build ./build
COPY --from=builder /app/package*.json ./
# COPY --from=builder /app/*.{js,json} ./

EXPOSE 5000

CMD ["npm", "start"]
