name: Build and Push Auth Service Image

on:
  push:
    branches:
      - main
    paths:
      - 'auth-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: docker build -f auth-service/Dockerfile.prod -t ken027/ticketing-auth-service auth-service/.

      - name: Login to docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to docker hub
        run: docker push ken027/ticketing-auth-service
