name: Payment Service Tests
on:
  pull_request:
    paths:
      - 'payment-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🧪 Run dev tests
        run: cd payment-service && npm install && npm run test:ci
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          STRIPE_PUBLISH_KEY: ${{ secrets.STRIPE_PUBLISH_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
